# Bot presence config

# online, idle, dnd, invisible
status: dnd

activity:
  # playing, watching, listening, streaming
  type: listening
  name: "Waterparks"

# Memory management
mem_max: 4096 # tokens

threshold: # normalized scale
  upper: 0.95 # Begin trimming
  lower: 0.75 # End trimming

