#                                                .__                 __   
# ______   ___________  __________   ____ _____  |  |   ____ _______/  |_ 
# \____ \_/ __ \_  __ \/  ___/  _ \ /    \\__  \ |  |  / ___\\____ \   __\
# |  |_> >  ___/|  | \/\___ (  <_> )   |  \/ __ \|  |_/ /_/  >  |_> >  |  
# |   __/ \___  >__|  /____  >____/|___|  (____  /____|___  /|   __/|__|  
# |__|        \/           \/           \/     \/    /_____/ |__|         

#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

#---------------------------------------+
#         Bot Discord Presence          |
#---------------------------------------+
# online, idle, dnd, invisible
status: dnd

activity:
  # playing, watching, listening, streaming
  type: listening
  name: "Chippin' In"

#---------------------------------------+
#           Memory Management           |
#---------------------------------------+
mem_max: 4096 # tokens
mem_sync: 0.25 # 25% of capacity is synced


#---------------------------------------+
#             OpenAI Models             |
#---------------------------------------+
chat:
  model : gpt-4o # (gpt-4o, gpt-4-turbo)
  temp  : 0.55 # [0, 2]
  tokens: 500 # Words = 3/4 tokens

vision:
  detail: auto # low/auto/high
