#                                                .__                 __   
# ______   ___________  __________   ____ _____  |  |   ____ _______/  |_ 
# \____ \_/ __ \_  __ \/  ___/  _ \ /    \\__  \ |  |  / ___\\____ \   __\
# |  |_> >  ___/|  | \/\___ (  <_> )   |  \/ __ \|  |_/ /_/  >  |_> >  |  
# |   __/ \___  >__|  /____  >____/|___|  (____  /____|___  /|   __/|__|  
# |__|        \/           \/           \/     \/    /_____/ |__|         

#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

#---------------------------------------+
#         Bot Discord Presence          |
#---------------------------------------+
# online, idle, dnd, invisible
status: dnd

activity:
  # playing, watching, listening, streaming
  type: listening
  name: "Samurai"

#---------------------------------------+
#           Memory Management           |
#---------------------------------------+
mem_max: 8096 # tokens

threshold: # normalized scale
  upper: 0.95 # Begin trimming
  lower: 0.75 # End trimming

#---------------------------------------+
#             OpenAI Models             |
#---------------------------------------+
chat:
  model : gpt-4o
  temp  : 0.35
  tokens: 500

vision:
  model : gpt-4o
  tokens: 250
  # low/auto/high
  detail: auto
