#                                                .__                 __   
# ______   ___________  __________   ____ _____  |  |   ____ _______/  |_ 
# \____ \_/ __ \_  __ \/  ___/  _ \ /    \\__  \ |  |  / ___\\____ \   __\
# |  |_> >  ___/|  | \/\___ (  <_> )   |  \/ __ \|  |_/ /_/  >  |_> >  |  
# |   __/ \___  >__|  /____  >____/|___|  (____  /____|___  /|   __/|__|  
# |__|        \/           \/           \/     \/    /_____/ |__|         

#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

#---------------------------------------+
#         Bot Discord Presence          |
#---------------------------------------+
# online, idle, dnd, invisible
status: dnd

activity:
  # playing, watching, listening, streaming
  type: listening
  name: "Hail the Sun"

#---------------------------------------+
#           Memory Management           |
#---------------------------------------+
mem_max: 8096 # tokens

threshold: # normalized scale
  upper: 0.95 # Begin trimming
  lower: 0.75 # End trimming

#---------------------------------------+
#              ElevenLabs               |
#---------------------------------------+
voice:
  id        : k2GEvsgcUkWzL3T2Q4F0
  stability : 0.5
  style     : 0.2
  similarity: 0.8
  boost     : True
  
  # 1. eleven_turbo_v2 (Low Quality, Fast)
  # 2. eleven_multilingual_v2 (High Quality, Slow) - Not Recommended!
  model: eleven_turbo_v2

#---------------------------------------+
#             OpenAI Models             |
#---------------------------------------+
chat:
  model : ft:gpt-3.5-turbo-1106:personal::8Ibhmf2N
  temp  : 0.55
  tokens: 512

vision:
  model : gpt-4-vision-preview
  tokens: 250
  # low/auto/high
  detail: auto

whisper:
  model: whisper-1
  lang : en

#---------------------------------------+
#    Voice Activity Detection (VAD)     |
#---------------------------------------+
# Agressiveness [1-3]
mode    : 3
# Frame duration [10-30] ms
duration: 30
# Smoothing
smoothing: 5

#---------------------------------------+
#             Voice Channel             |
#---------------------------------------+
# How long idle in VC (alone) in seconds
idle: 60